services:

  db:
    image: postgres:17

    environment:
      POSTGRES_DB: olist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PG_PASSWORD}

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./olist-data:/app/olist-data:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  data-loader:
    build:
      context: ./docker/data-loader

    environment:
      KAGGLE_API_TOKEN: ${KAGGLE_API_TOKEN:-}
      KAGGLE_DATASET: olistbr/brazilian-ecommerce

      PGHOST: db
      PGPORT: 5432
      PGDATABASE: olist
      PGUSER: postgres
      PGPASSWORD: ${PG_PASSWORD}

    volumes:
      - data_loader_venv:/app/.venv
      - ./docker/data-loader:/app/docker/data-loader
      - ./olist-data:/app/olist-data

    depends_on:
      db:
        condition: service_healthy


  sql-runner:
    build:
      context: ./docker/sql-runner

    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: olist
      PGUSER: postgres
      PGPASSWORD: ${PG_PASSWORD}

    volumes:
      - ./sql:/app/sql:ro
      - ./olist-data:/app/olist-data:ro

    depends_on:
      db:
        condition: service_healthy

    command: ["sleep", "infinity"]


volumes:
  postgres_data:
  data_loader_venv: