[project]
name = "data-loader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "edne-correios-loader>=1.2.0",
    "kaggle>=2.2.4",
    "pandas>=3.0.6",
    "psycopg[binary]>=3.3.6",
    "requests>=2.34.2",
    "xlrd>=2.0.2",
]
